apiVersion: v1
kind: Namespace
metadata:
  name: test-app
---
apiVersion: v1
kind: Pod
metadata:
  name: test-client
  namespace: test-app
spec:
  containers:
  - name: test-client
    image: busybox
    command: [ "sleep", "3600" ]
---
## NOTE - Service needs to exist in both clusters
apiVersion: v1
kind: Service
metadata:
  name: echo-server
  namespace: test-app
  annotations:
    io.cilium/global-service: "true"
spec:
  type: ClusterIP
  selector:
    app: echo-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080